# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af21aa34903428ccfaaaae440b6ba1ed06a902c6f6635aea5ac51ad013ca79fdd675940fbfe652bbbc3788648727b78e2c722394f07357a737e579484d34f0a4

test:
  secret_key_base: 885a03185d5ecbca23e49cff91fbb6ede1cde5ab5f98d1919687c1925fb7d50fac3a9197200f80367937c297f70b40b91f925e6acd2fdc5320a71f19c2f42a0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
